Repository PavelKovalev1444/Summer-Practice-2021, pull requests merged in 2021-07, with the labels that each got.

#10 Final ultimate project version
  Final_project/FileOpening.java
  Final_project/Main.java
  Final_project/MatrixAdapterFabric.java
  Final_project/MouseAdapterFabric.java
  Final_project/ReleaseFloyd.java
  Final_project/ReleaseFloydTester.java
  Final_project/TableAdapterFabric.java
  Final_project/VertexEnumerator.java
  Final_project/testing.java
  GraphVizualizator.jar
Labels: FINAL STAGE, Final Release

#2 Specification and report
  Report_Practice_2021.pdf
Labels: FINAL STAGE, STAGE 1, STAGE 2, documentation

#3 Initial version of the project
  GraphVizualizator/GraphVizualizator.iml
  GraphVizualizator/pom.xml
  GraphVizualizator/src/main/java/Main.java
  GraphVizualizator/src/main/java/VertexEnumerator.java
  GraphVizualizator/target/classes/Main$1.class
  GraphVizualizator/target/classes/Main$2.class
  GraphVizualizator/target/classes/Main$3.class
  GraphVizualizator/target/classes/Main$4.class
  GraphVizualizator/target/classes/Main$5.class
  GraphVizualizator/target/classes/Main.class
Labels: STAGE 1

#5 Floyd-Warshall algorythm
  FloydWarshall.java
Labels: STAGE 1

#9 Release version of project
  GraphVizualizator/src/FileOpening.java
  GraphVizualizator/src/Main.java
  GraphVizualizator/src/MatrixAdapterFabric.java
  GraphVizualizator/src/MouseAdapterFabric.java
  GraphVizualizator/src/ReleaseFloyd.java
  GraphVizualizator/src/TableAdapterFabric.java
  GraphVizualizator/src/VertexEnumerator.java
Labels: Release
